image: registry.gitlab.com/islandoftex/images/texlive:latest

build:
  script:
    - pdflatex ./presi_template/presentation.tex
    - biber ./presi_template/presentation
    - pdflatex ./presi_template/presentation.tex
  after_script:
    - cat ./presi_template/presentation.log
  artifacts:
    paths:
      - ./presi_template/presentation.pdf
