
stages:
  - build
  - deploy

latex-build: 
  image: registry.gitlab.com/islandoftex/images/texlive:latest
  stage: build
  script:
      - cd presi_template
      - pdflatex presentation.tex
      - biber presentation
      - pdflatex presentation.tex
      - cd ..
      - cd pflichtenheft
      - pdflatex main.tex
  artifacts:
    paths:
      - ./presi_template/presentation.pdf
      - ./pflichtenheft/main.pdf

java-test:
  image: eclipse-temurin:21-jdk-noble
  stage: build
  script:
    - gradle build

image-build:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master
