image: registry.gitlab.com/islandoftex/images/texlive:latest

build:
  script:
    - cd presi_template
    - pdflatex presentation.tex
    - cd ..
    - cd pflichtenheft
    - pdflatex .Pflichtenheft.tex
  artifacts:
    paths:
      - ./presi_template/presentation.pdf
      - ./pflichtenheft/Pflichtenheft.pdf
