spring:
  security:
    oauth2:
      client:
        registration:
          kit:
            client-id: ${KIT_CLIENT_ID}
            client-secret: ${KIT_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Kit
        provider:
            kit:
              issuer-uri: "https://oidc.scc.kit.edu/auth/realms/kit"
              authorization-uri: "https://oidc.scc.kit.edu/auth/realms/kit/protocol/openid-connect/auth"
              token-uri: "https://oidc.scc.kit.edu/auth/realms/kit/protocol/openid-connect/token"
              user-info-uri: "https://oidc.scc.kit.edu/auth/realms/kit/protocol/openid-connect/userinfo"

  application:
    name: Soli
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgres://127.0.0.1:5432/soli"
    username: soli
    password: john_soli
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:dev}"
  docker:
    compose:
      skip:
        in-tests: false
server:
  error:
    path: /error
    whitelabel:
      enabled: false