spring:
  application:
    name: Soli
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgres://127.0.0.1:5432/soli"
    username: soli
    password: john_soli
  profiles:
    active: "${SPRING_PROFILES_ACTIVE:dev}"
  docker:
    compose:
      skip:
        in-tests: false