spring:
  devtools:
    restart:
      additional-paths: ./src/main/jte

soli:
  development-mode: true
  administrator:
    password: "{noop}password"
  guest:
    marker: "guest"
  hostname: "http://localhost:8080"
