name: Gradle Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: gradle/actions/wrapper-validation@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    - name: Build with Gradle
      run: ./gradlew clean build
    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker Image
      run: |
        export IMAGE_NAME=`echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'`:latest
        docker build -t "ghcr.io/$IMAGE_NAME" .
        docker push "ghcr.io/$IMAGE_NAME"
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4