name: Gradle Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - uses: gradle/actions/wrapper-validation@v4.2.0
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@4a0951b3dce72986ec5a30ca053bf7390e736564
    - name: Build and test with Gradle
      run: ./gradlew clean build test --scan
    - name: Login to Docker
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build Docker Image
      run: |
        export IMAGE_NAME=`echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]'`:latest
        docker build -t "ghcr.io/$IMAGE_NAME" .
        docker push "ghcr.io/$IMAGE_NAME"

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - uses: gradle/actions/wrapper-validation@v4.2.0
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@v4.2.0
