name: LaTeX Build

on:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    container: ghcr.io/solidarische-raumnutzung/docker-texlive
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Build
        run: |
          cd presi_template
          pdflatex presentation.tex
          biber presentation
          pdflatex presentation.tex
          cd ../pflichtenheft
          pdflatex main.tex
          makeglossaries main
          pdflatex main.tex
          pdflatex main.tex
          cd ../entwurfsheft
          wget https://solidarische-raumnutzung.github.io/DocTeX/doctex.jar
          java -jar doctex.jar --output=./javadoc ../src/main/java edu.kit.hci.soli
          pdflatex main.tex
          makeglossaries main
          pdflatex main.tex
          pdflatex main.tex
          cd ..
          mkdir -p pages
          mv ./presi_template/presentation.pdf ./pages/presentation.pdf
          mv ./pflichtenheft/main.pdf ./pages/pflichtenheft.pdf
          mv ./entwurfsheft/main.pdf ./pages/entwurfsheft.pdf
          python3 .github/genindex.py pages
      - name : Commit javadoc
        run: |
          git config --global user.name github-actions
          git config --global user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add .
          git commit -m '[ci: javadoc] ${{ github.event.head_commit.message }}'
          git push
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: 'pages'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
